import { serverEnv } from "@/lib/env";
import { FileMap } from "./types";

export interface GitHubExportResult {
  success: boolean;
  repoUrl: string;
  repoName: string;
  error?: string;
}

export class GitHubError extends Error {
  constructor(
    message: string,
    public readonly status?: number,
    cause?: unknown,
  ) {
    super(message, { cause });
    this.name = "GitHubError";
  }
}

/**
 * Export files to a new GitHub repository
 */
export async function exportToGitHub(
  repoName: string,
  files: FileMap,
  description?: string
): Promise<GitHubExportResult> {
  const token = serverEnv.GITHUB_TOKEN;
  
  if (!token) {
    return {
      success: false,
      repoUrl: "",
      repoName,
      error: "GitHub token not configured. Set GITHUB_TOKEN environment variable.",
    };
  }

  try {
    const { Octokit } = await import("@octokit/rest");
    const octokit = new Octokit({ auth: token });

    // Get authenticated user
    const { data: user } = await octokit.users.getAuthenticated();
    const owner = user.login;

    // Check if repo already exists
    try {
      await octokit.repos.get({ owner, repo: repoName });
      return {
        success: false,
        repoUrl: "",
        repoName,
        error: `Repository "${repoName}" already exists`,
      };
    } catch {
      // Repo doesn't exist, continue
    }

    // Create the repository
    const { data: repo } = await octokit.repos.createForAuthenticatedUser({
      name: repoName,
      description: description || `Generated by AI App Builder`,
      private: true,
      auto_init: false,
    });

    // CI/CD workflow content
    const ciWorkflow = `name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Type check
        run: npx tsc --noEmit
      
      - name: Lint
        run: npm run lint
      
      - name: Build
        run: npm run build
        env:
          SKIP_ENV_VALIDATION: true

  deploy-preview:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Preview
        run: echo "Preview deployment triggered for PR \${{ github.event.number }}"
`;

    // README content (used if README.md is not already in files)
    const readmeContent = `# ${repoName}

Generated by AI App Builder - Phase 4 Export

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

## Tech Stack
- Next.js 15
- React 19
- TypeScript
- Tailwind CSS

## Deploy

[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/clone?repository-url=https://github.com/${owner}/${repoName})
`;

    // Create blobs for each project file
    const fileBlobs = await Promise.all(
      Object.entries(files).map(async ([path, content]) => {
        const { data: blob } = await octokit.git.createBlob({
          owner,
          repo: repoName,
          content: Buffer.from(content).toString("base64"),
          encoding: "base64",
        });
        return { path, sha: blob.sha };
      })
    );

    // Build tree items from project file blobs
    const treeItems: Array<{
      path: string;
      mode: "100644";
      type: "blob";
      content?: string;
      sha?: string;
    }> = fileBlobs.map(({ path, sha }) => ({
      path,
      mode: "100644" as const,
      type: "blob" as const,
      sha,
    }));

    // Add CI workflow
    treeItems.push({
      path: ".github/workflows/ci.yml",
      mode: "100644",
      type: "blob",
      content: ciWorkflow,
    });

    // Add README.md if not already present in the exported files
    if (!files["README.md"]) {
      treeItems.push({
        path: "README.md",
        mode: "100644",
        type: "blob",
        content: readmeContent,
      });
    }

    // Create a tree with all files (initial commit has no parent)
    const { data: tree } = await octokit.git.createTree({
      owner,
      repo: repoName,
      tree: treeItems,
    });

    // Create initial commit (no parents for first commit)
    const { data: commit } = await octokit.git.createCommit({
      owner,
      repo: repoName,
      message: "Initial commit: Generated by AI App Builder",
      tree: tree.sha,
      parents: [],
    });

    // Update the reference to point to the new commit
    await octokit.git.updateRef({
      owner,
      repo: repoName,
      ref: "heads/main",
      sha: commit.sha,
    });

    return {
      success: true,
      repoUrl: repo.html_url,
      repoName,
    };
  } catch (error) {
    console.error("GitHub export error:", error);
    
    if (error instanceof GitHubError) {
      throw error;
    }

    const message = error instanceof Error ? error.message : "Unknown error";
    
    return {
      success: false,
      repoUrl: "",
      repoName,
      error: `GitHub export failed: ${message}`,
    };
  }
}

/**
 * Check if GitHub integration is available
 */
export function isGitHubAvailable(): boolean {
  return !!serverEnv.GITHUB_TOKEN;
}

/**
 * Get repository URL format
 */
export function getGitHubRepoUrl(owner: string, repo: string): string {
  return `https://github.com/${owner}/${repo}`;
}
