import { serverEnv } from "@/lib/env";
import { FileMap } from "./types";

export interface GitHubExportResult {
  success: boolean;
  repoUrl: string;
  repoName: string;
  error?: string;
}

export class GitHubError extends Error {
  constructor(
    message: string,
    public readonly status?: number,
    cause?: unknown,
  ) {
    super(message, { cause });
    this.name = "GitHubError";
  }
}

/**
 * Export files to a new GitHub repository
 */
export async function exportToGitHub(
  repoName: string,
  files: FileMap,
  description?: string
): Promise<GitHubExportResult> {
  const token = serverEnv.GITHUB_TOKEN;
  
  if (!token) {
    return {
      success: false,
      repoUrl: "",
      repoName,
      error: "GitHub token not configured. Set GITHUB_TOKEN environment variable.",
    };
  }

  try {
    const { Octokit } = await import("@octokit/rest");
    const octokit = new Octokit({ auth: token });

    // Get authenticated user
    const { data: user } = await octokit.users.getAuthenticated();
    const owner = user.login;

    // Check if repo already exists
    try {
      await octokit.repos.get({ owner, repo: repoName });
      return {
        success: false,
        repoUrl: "",
        repoName,
        error: `Repository "${repoName}" already exists`,
      };
    } catch {
      // Repo doesn't exist, continue
    }

    // Create the repository
    const { data: repo } = await octokit.repos.createForAuthenticatedUser({
      name: repoName,
      description: description || `Generated by AI App Builder`,
      private: true,
      auto_init: false,
    });

    // Get the default branch ref
    const { data: ref } = await octokit.git.getRef({
      owner,
      repo: repoName,
      ref: "heads/main",
    });

    const baseTreeSha = ref.object.sha;

    // Create blobs for each file
    const fileBlobs = await Promise.all(
      Object.entries(files).map(async ([path, content]) => {
        const { data: blob } = await octokit.git.createBlob({
          owner,
          repo: repoName,
          content: Buffer.from(content).toString("base64"),
          encoding: "base64",
        });
        return { path, sha: blob.sha };
      })
    );

    // Create a tree with all files
    const { data: tree } = await octokit.git.createTree({
      owner,
      repo: repoName,
      base_tree: baseTreeSha,
      tree: fileBlobs.map(({ path, sha }) => ({
        path,
        mode: "100644" as const,
        type: "blob" as const,
        sha,
      })),
    });

    // Create a commit
    const { data: commit } = await octokit.git.createCommit({
      owner,
      repo: repoName,
      message: "Initial commit: Generated by AI App Builder",
      tree: tree.sha,
      parents: [baseTreeSha],
    });

    // Update the reference to point to the new commit
    await octokit.git.updateRef({
      owner,
      repo: repoName,
      ref: "heads/main",
      sha: commit.sha,
    });

    // Create a README if not present
    if (!files["README.md"]) {
      const readmeContent = `# ${repoName}

${description || "Generated by AI App Builder"}

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

## Project Structure

${Object.keys(files).map(f => `- \`${f}\``).join("\n")}
`;

      await octokit.repos.createOrUpdateFileContents({
        owner,
        repo: repoName,
        path: "README.md",
        message: "Add README",
        content: Buffer.from(readmeContent).toString("base64"),
      });
    }

    return {
      success: true,
      repoUrl: repo.html_url,
      repoName,
    };
  } catch (error) {
    console.error("GitHub export error:", error);
    
    if (error instanceof GitHubError) {
      throw error;
    }

    const message = error instanceof Error ? error.message : "Unknown error";
    
    return {
      success: false,
      repoUrl: "",
      repoName,
      error: `GitHub export failed: ${message}`,
    };
  }
}

/**
 * Check if GitHub integration is available
 */
export function isGitHubAvailable(): boolean {
  return !!serverEnv.GITHUB_TOKEN;
}

/**
 * Get repository URL format
 */
export function getGitHubRepoUrl(owner: string, repo: string): string {
  return `https://github.com/${owner}/${repo}`;
}
